#!/bin/bash
 
read -r -p "Are you sure you want to start installation ? [Y/n] " input
 
case $input in
    [yY][eE][sS]|[yY])
 echo "Operation confirmed"
 ;;
    [nN][oO]|[nN])
 echo "Operation cancelled"
       exit;;
    *)
 echo "Invalid input..."
 exit 1
 ;;
esac

sudo mkdir /usr/RoxMCLauncher
cd /usr/RoxMCLauncher
sudo curl http://downtherack.free.fr/RoxMCLauncher/RMCL.jar --output RMCL.jar
sudo curl https://raw.githubusercontent.com/Romanio0089/RoxMCLauncher/master/Linux/RMCLoader.sh --output RMCLoader.sh
sudo curl https://raw.githubusercontent.com/Romanio0089/RoxMCLauncher/master/Linux/RoxMCLauncherApp.zip --output RoxMCLauncherApp.zip
sudo curl http://downtherack.free.fr/RoxMCLauncher/logormclhighres.png --output logormclhighres.png
sudo unzip RoxMCLauncherApp.zip -d ~/Applications/
cd ~/Applications/
sudo chmod +x RoxMCLauncher.app
echo "RoxMCLauncher has been installed ! To run it, search for RoxMCLauncher in the applications or execute the command: java -jar /usr/RoxMCLauncher/RMCL.jar"